/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MotorGrafico */

#ifndef _Included_MotorGrafico
#define _Included_MotorGrafico
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MotorGrafico
 * Method:    inicializar
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_MotorGrafico_inicializar
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     MotorGrafico
 * Method:    atualizarNeuronio
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_MotorGrafico_atualizarNeuronio
  (JNIEnv *, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
